spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

  mvc:
    static-path-pattern: /static/**

  profiles:
    active: local

  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
