spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql

  h2:
    console:
      enabled: true
